-- ============================================================================
-- Migration: operators table — complete snapshot
-- Date: 2026-05-07
-- 108 entries (30 flight schools, 78 operators)
-- Source: Vectored operator database v3 (May 2026)
-- ============================================================================

DROP TABLE IF EXISTS public.operators CASCADE;

CREATE TABLE public.operators (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name              text NOT NULL,
  slug              text UNIQUE NOT NULL,
  state             text NOT NULL,
  bases             text NOT NULL,
  primary_icao      text,
  latitude          numeric(8,5) NOT NULL,
  longitude         numeric(8,5) NOT NULL,
  website           text,
  phone             text,
  email             text,
  key_personnel     text,
  fleet             text,
  operations        text,
  min_hours         text,
  min_hours_numeric integer,
  hires_low_hour    text,
  part_141_142      text,
  aircraft_category text NOT NULL DEFAULT 'fixed_wing',
  is_flight_school  boolean NOT NULL DEFAULT false,
  background_tips   text,
  forum_sentiment   text,
  source            text,
  last_verified     date,
  published         boolean NOT NULL DEFAULT false,
  claimed_by        uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  claim_status      text NOT NULL DEFAULT 'unclaimed',
  claimed_at        timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT operators_state_check
    CHECK (state IN ('NSW','VIC','QLD','WA','SA','TAS','NT','ACT','National')),
  CONSTRAINT operators_aircraft_category_check
    CHECK (aircraft_category IN ('fixed_wing','helicopter','both')),
  CONSTRAINT operators_claim_status_check
    CHECK (claim_status IN ('unclaimed','pending','verified','rejected'))
);

CREATE INDEX idx_operators_state           ON public.operators(state);
CREATE INDEX idx_operators_published       ON public.operators(published);
CREATE INDEX idx_operators_slug            ON public.operators(slug);
CREATE INDEX idx_operators_is_flight_school ON public.operators(is_flight_school);

CREATE OR REPLACE FUNCTION public.set_operators_updated_at()
RETURNS trigger AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS operators_updated_at ON public.operators;
CREATE TRIGGER operators_updated_at
  BEFORE UPDATE ON public.operators
  FOR EACH ROW EXECUTE FUNCTION public.set_operators_updated_at();

ALTER TABLE public.operators ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read flight schools" ON public.operators;
CREATE POLICY "Public read flight schools" ON public.operators
  FOR SELECT TO anon, authenticated
  USING (published = true AND is_flight_school = true);

DROP POLICY IF EXISTS "CPL tier read all operators" ON public.operators;
CREATE POLICY "CPL tier read all operators" ON public.operators
  FOR SELECT TO authenticated
  USING (
    published = true AND EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
        AND profiles.tier IN ('founding_pilot','cpl')
        AND (profiles.access_expires_at IS NULL OR profiles.access_expires_at > now())
    )
  );

-- ============================================================================
-- Seed data (108 entries)
-- ============================================================================

INSERT INTO public.operators (
  name,slug,state,bases,primary_icao,latitude,longitude,
  website,phone,email,key_personnel,fleet,operations,
  min_hours,min_hours_numeric,hires_low_hour,part_141_142,
  aircraft_category,is_flight_school,background_tips,
  source,last_verified,published
) VALUES
  ('Corporate Air - Canberra','corporate-air-canberra','ACT','Canberra','YSCB',-35.3053,149.1933,'https://corporate-air.com.au/','1300 441 000',NULL,NULL,'Saab 340B, Metro 23, Cessna 441 Conquest, jets','Executive charter, FIFO, aeromedical, freight','1000+',1000,'No','No','fixed_wing',false,'Corporate Air base at Canberra. Headquartered in Canberra (est. 1972). Parent of Link Airways. One of the longest-running aviation services in eastern/southern Australia. Mix of corporate charter, government, FIFO, freight, aeromedical.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Air Link','air-link','NSW','Dubbo','YSDU',-32.2167,148.5747,'https://www.airlinkairlines.com.au','02 6884 2435',NULL,NULL,'Saab 340, Metro','RPT, charter','500+',500,'Possibly','No','fixed_wing',false,'Subsidiary of REX. Dubbo-based. RPT and charter across regional NSW. May take lower-hour F/Os.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Airspeed Aviation - Dubbo','airspeed-aviation-dubbo','NSW','Dubbo','YSDU',-32.2189,148.5697,'https://www.airspeedflightschool.com.au/','1300 247 773','info@airspeedaviation.com.au',NULL,'Training and charter fleet','Training, some charter','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Airspeed Aviation base at Dubbo. Family-owned NSW operator headquartered at Scone, with multiple regional bases. Provides full RPL/PPL/CPL training plus instructor ratings and charter to support equine, beef, and coal industries.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Airspeed Aviation - Gunnedah','airspeed-aviation-gunnedah','NSW','Gunnedah','YGDH',-30.9592,150.2547,'https://www.airspeedflightschool.com.au/','1300 247 773','info@airspeedaviation.com.au',NULL,'Training and charter fleet','Training, some charter','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Airspeed Aviation base at Gunnedah. Family-owned NSW operator headquartered at Scone, with multiple regional bases. Provides full RPL/PPL/CPL training plus instructor ratings and charter to support equine, beef, and coal industries.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Airspeed Aviation - Scone','airspeed-aviation-scone','NSW','Scone','YSCO',-32.0357,150.8326,'https://www.airspeedflightschool.com.au/','1300 247 773','info@airspeedaviation.com.au',NULL,'Training and charter fleet','Training, some charter','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Airspeed Aviation base at Scone. Family-owned NSW operator headquartered at Scone, with multiple regional bases. Provides full RPL/PPL/CPL training plus instructor ratings and charter to support equine, beef, and coal industries.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Airspeed Aviation - Shellharbour','airspeed-aviation-shellharbour','NSW','Shellharbour','YSHL',-34.5604,150.7905,'https://www.airspeedflightschool.com.au/','1300 247 773','info@airspeedaviation.com.au',NULL,'Training and charter fleet','Training, some charter','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Airspeed Aviation base at Shellharbour. Family-owned NSW operator headquartered at Scone, with multiple regional bases. Provides full RPL/PPL/CPL training plus instructor ratings and charter to support equine, beef, and coal industries.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Airspeed Aviation - Tamworth','airspeed-aviation-tamworth','NSW','Tamworth','YSTW',-31.0845,150.8484,'https://www.airspeedflightschool.com.au/','1300 247 773','info@airspeedaviation.com.au',NULL,'Training and charter fleet','Training, some charter','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Airspeed Aviation base at Tamworth. Family-owned NSW operator headquartered at Scone, with multiple regional bases. Provides full RPL/PPL/CPL training plus instructor ratings and charter to support equine, beef, and coal industries.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Bankstown Flying School','bankstown-flying-school','NSW','Sydney (Bankstown)','YSBK',-33.9244,151.0203,'https://www.bankstownflying.com.au/','02 9707 3822','enquiries@bankstownflying.com.au',NULL,'C172, PA-28, Cirrus SR series','Training (RPL, PPL, CPL, MECIR, Cirrus)','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Flexible pilot training RPL to MECIR at Bankstown. NSW-certified Cirrus training centre — useful for pilots targeting corporate or owner-pilot roles. Flexible scheduling.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Basair','basair','NSW','Sydney (Bankstown)','YSBK',-33.9244,151.0203,'https://www.basair.com.au/','02 9791 0111','info@basair.com.au',NULL,'C172, PA-28, multi-engine fleet','Training (RPL, PPL, CPL, ATPL, MECIR, IFR, Instructor)','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Basair Australia Group — parent of Sydney Aviators. Long-established Bankstown operation. Full RPL to ATPL pathway. Part-time and full-time training options. Well-regarded for commercial pilot production.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Coffs Coast Skydiving','coffs-coast-skydiving','NSW','Coffs Harbour','YCFS',-30.3208,153.1161,NULL,NULL,NULL,NULL,'C206, C208','Skydive operations','200',200,'Yes','No','fixed_wing',false,'Skydive pilot positions. Good hour building. C206/C208 experience.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Corporate Air - Goulburn','corporate-air-goulburn','NSW','Goulburn','YGLB',-34.8068,149.7343,'https://corporate-air.com.au/','1300 441 000',NULL,NULL,'Saab 340B, Metro 23, Cessna 441 Conquest, jets','Executive charter, FIFO, aeromedical, freight','1000+',1000,'No','No','fixed_wing',false,'Corporate Air base at Goulburn. Headquartered in Canberra (est. 1972). Parent of Link Airways. One of the longest-running aviation services in eastern/southern Australia. Mix of corporate charter, government, FIFO, freight, aeromedical.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Corporate Air - Sydney','corporate-air-sydney','NSW','Sydney','YSSY',-33.95,151.1817,'https://corporate-air.com.au/','1300 441 000',NULL,NULL,'Saab 340B, Metro 23, Cessna 441 Conquest, jets','Executive charter, FIFO, aeromedical, freight','1000+',1000,'No','No','fixed_wing',false,'Corporate Air base at Sydney. Headquartered in Canberra (est. 1972). Parent of Link Airways. One of the longest-running aviation services in eastern/southern Australia. Mix of corporate charter, government, FIFO, freight, aeromedical.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Curtis Aviation','curtis-aviation','NSW','Bankstown','YSBK',-33.9244,151.0203,'https://www.curtisaviation.com.au',NULL,NULL,NULL,'C172, PA-28, C182, C210','Training, charter','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Bankstown flight school. Training plus charter operations. C210 endorsement available.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('FlyPelican','flypelican','NSW','Newcastle (Williamtown)','YWLM',-32.7949,151.8344,'https://www.flypelican.com.au/',NULL,NULL,NULL,'BAe Jetstream 32','RPT','500+',500,'No','No','fixed_wing',false,'Regional RPT services. Newcastle-based but operates to Adelaide.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Link Airways (formerly Fly Corporate)','link-airways','NSW','Brisbane / Sydney / Newcastle','YSBK',-33.9244,151.0203,'https://www.linkairways.com',NULL,NULL,NULL,'Saab 340, Metro','RPT, charter','800+',800,'No','No','fixed_wing',false,'Regional airline. RPT services Sydney-Tamworth-Coffs Harbour-Newcastle and more. Not for low-hour pilots but career progression target.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Panair / Panorama Airways','panair-panorama-airways','NSW','Bathurst (Raglan)','YBTH',-33.4137,149.655,'https://www.panairflighttraining.com/','02 6337 3737','admin@panairflighttraining.com',NULL,'Piper Warrior, Piper Seminole, Cessna 400-series, Piper Chieftain, warbirds','Training, charter, FIFO, scenic, aerial photography, maintenance','Unknown',NULL,'Possibly','Yes (141)','fixed_wing',true,'Largest operation at Bathurst Airport, operating since 1994/96. Comprehensive flight training to CPL + multi-engine + instrument + instructor. CASA-approved in-house exams up to PPL. Also runs charter, FIFO, aerial photography, and a maintenance facility (incl. warbirds).','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Qantas Group (QantasLink)','qantas-group','NSW','Various (national)','YSSY',-33.9461,151.1772,'https://www.qantas.com/au/en/about-us/our-company/careers.html',NULL,NULL,NULL,'Dash 8, B717, A320 family, B737, B787, A330, A380','RPT','3000+',3000,'No','No','fixed_wing',false,'Australia''s flag carrier. QantasLink regional F/O roles at 1500+ hours. Mainline at 3000+. Long-term career aspiration.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Red Baron Flight Training','red-baron-flight-training','NSW','Bankstown','YSBK',-33.9244,151.0203,'https://www.redbaron.com.au',NULL,NULL,NULL,'C172, PA-28, C182','Training','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Well-known Bankstown flight school. RPL to CPL training.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('REX Regional Express','rex-regional-express','NSW','Various (national)','YSSY',-33.9461,151.1772,'https://www.rex.com.au','13 17 13','careers@rex.com.au',NULL,'Saab 340B, B737','RPT','1500+',1500,'No','No','fixed_wing',false,'Australia''s largest independent regional airline. 60+ destinations. Cadet program available. Not for low-hour pilots but the primary career target for regional airline F/O at 1500+ hours.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Bankstown','rfds-bankstown','NSW','Sydney (Bankstown)','YSBK',-33.9244,151.0203,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Broken Hill','rfds-broken-hill','NSW','Broken Hill','YBHI',-32.0014,141.4722,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Dubbo','rfds-dubbo','NSW','Dubbo','YSDU',-32.2189,148.5697,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Lismore','rfds-lismore','NSW','Lismore','YLSM',-28.8303,153.2597,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Tamworth','rfds-tamworth','NSW','Tamworth','YSTW',-31.0845,150.8484,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Taree','rfds-taree','NSW','Taree','YTRE',-31.8886,152.5144,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Wagga Wagga','rfds-wagga-wagga','NSW','Wagga Wagga','YSWG',-35.1653,147.4661,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Wollongong','rfds-wollongong','NSW','Wollongong (Shellharbour)','YSHL',-34.5604,150.7905,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Skydive Australia - Byron Bay','skydive-australia-byron-bay','NSW','Tyagarah Airfield, Tyagarah',NULL,-28.5961,153.5483,'https://www.skydive.com.au',NULL,NULL,NULL,'Cessna 208 Caravan / Twin Otter (varies by location)','Skydive operations','200-250',200,'Yes','No','fixed_wing',false,'National skydive operator. Hires low-hour CPL pilots for jump-plane operations; valued first-job pathway for new commercial pilots.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Skydive Australia - Newcastle','skydive-australia-newcastle','NSW','Lake Macquarie Airport, Marks Point',NULL,-33.0662,151.651,'https://www.skydive.com.au',NULL,NULL,NULL,'Cessna 208 Caravan / Twin Otter (varies by location)','Skydive operations','200-250',200,'Yes','No','fixed_wing',false,'National skydive operator. Hires low-hour CPL pilots for jump-plane operations; valued first-job pathway for new commercial pilots.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Skydive Australia - Wollongong','skydive-australia-wollongong','NSW','Stuart Park, North Wollongong',NULL,-34.4104,150.899,'https://www.skydive.com.au',NULL,NULL,NULL,'Cessna 208 Caravan / Twin Otter (varies by location)','Skydive operations','200-250',200,'Yes','No','fixed_wing',false,'National skydive operator. Hires low-hour CPL pilots for jump-plane operations; valued first-job pathway for new commercial pilots.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Sydney Flying College (SFC)','sydney-flying-college','NSW','Sydney (Bankstown)','YSBK',-33.9244,151.0203,'https://www.sfcaero.com.au/','02 9709 8488','info@sfcaero.com.au',NULL,'C172, PA-28, multi-engine fleet','Training (RPL, PPL, CPL, ATPL, MECIR, IFR, Instructor)','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'One of Sydney''s largest and most established flight schools at Bankstown. Full pathway from RPL through to ATPL and instructor ratings. Strong reputation for professional pilot training.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Sydney Seaplanes','sydney-seaplanes','NSW','Rose Bay, Sydney',NULL,-33.8688,151.2554,'https://www.seaplanes.com.au/','02 9388 1978',NULL,NULL,'Cessna Caravan (float), DHC-2 Beaver','Scenic, charter, transfers','500+',500,'No','No','fixed_wing',false,'Iconic Sydney Harbour seaplane operator. Premium scenic and transfer flights. Float rating required.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('UNSW Aviation','unsw-aviation','NSW','Sydney (Bankstown)','YSBK',-33.9244,151.0203,'https://www.aviation.unsw.edu.au/','02 9791 3047','aviation@unsw.edu.au',NULL,'C172, multi-engine fleet, B737 simulator','Training (RPL, PPL, CPL, ATPL, MECIR, IFR, Instructor, B737 Sim)','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'University-based aviation program at Bankstown. Bachelor of Aviation degree paired with CASA-approved flight training. B737 full-motion simulator on site. Strong academic and practical combination — pathway to airline careers.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Wardair Flight Training','wardair-flight-training','NSW','Bathurst (Dubbo secondary)','YBTH',-33.4137,149.655,'https://wardair.com.au/','02 6337 3400','info@wardair.com.au',NULL,'Single-engine training fleet','Training (RPL, PPL, CPL, NVFR, IFR, instructor, multi-engine)','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Bathurst-based personalised flight training operation. Tailor-made packages at student''s pace. Strong in regional uncontrolled airspace exposure with proximity to Sydney basin controlled airspace for advanced training.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Air Frontier','air-frontier','NT','Darwin','YPDN',-12.4147,130.8769,'https://www.airfrontier.com.au','08 8947 0355',NULL,NULL,'C210, C206, BN-2 Islander, King Air','Charter, freight, aerial work','Unknown',NULL,'Possibly','No','fixed_wing',false,'One of the longest running charter companies in the NT. Remote area specialist. Good for building bush strip experience.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Airnorth','airnorth','NT','Darwin','YPDN',-12.4147,130.8769,'https://www.airnorth.com.au','08 8920 4000','admin@airnorth.com.au',NULL,'E170, E120 Brasilia, Metro','RPT, charter, FIFO','1000+',1000,'No','No','fixed_wing',false,'Second longest operating Australian airline (40+ years). 220+ services/week across NT, WA, QLD, VIC and Timor-Leste. Not for low-hour pilots but good career progression target at 1000+ hours.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Chartair','chartair','NT','Darwin / Alice Springs','YPDN',-12.4147,130.8769,'https://www.chartair.com.au','08 8945 0666','careers@chartair.com.au','Part of Aviation Logistics Group','C210, C208 Grand Caravan, C441 Conquest','Charter, RPT, freight','300 total',300,'Yes','No','fixed_wing',false,'Australia''s largest GA charter operator. 3-year ''apprenticeship'' model — invest in development. C210 VFR → C208 → C441 turbine progression. Part 145 maintenance. Submit CV via website. Visit Darwin or Alice Springs base in person.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Charter North','charter-north','NT','Darwin','YPDN',-12.4147,130.8769,NULL,'08 8941 1011',NULL,NULL,'C210, C206','Charter, freight','Unknown',NULL,'Possibly','No','fixed_wing',false,'Small Darwin-based charter operator. Remote community services.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Flight Standards','flight-standards','NT','Darwin / Alice Springs','YPDN',-12.4147,130.8769,'https://flightstandards.com.au',NULL,NULL,'Cameron Marchant (Chief Pilot)','C210, PA-32 Saratoga, GA8 Airvan','Training, charter','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Offers ''GA Ready'' course — 6-day transition course for fresh CPL holders. C210 endorsement, bush strip ops, LAHSO training, Darwin airspace familiarisation, maintenance training. Also bases in Perth and Brisbane. Worth the investment.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Fly Uluru','fly-uluru','NT','Yulara (Uluru)','YAYE',-25.1861,130.9756,'https://www.flyuluru.com.au/',NULL,NULL,NULL,'GA8 Airvan, C210','Scenic flights','Unknown',NULL,'Possibly','No','fixed_wing',false,'Scenic flights over Uluru (Ayers Rock), Kata Tjuta and the Red Centre. One of the oldest tour operators at Uluru, operating since 1989. Iconic flying over the red desert landscape.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Hardy Aviation / Fly Tiwi','hardy-aviation-fly-tiwi','NT','Darwin','YPDN',-12.4147,130.8769,'https://hardyaviation.com.au','08 8947 2022',NULL,'Founded by John Hardy (1991)','C210, C402, C404, C208, C441, Metro','Charter, RPT, freight','Unknown',NULL,'Possibly','No','fixed_wing',false,'Fleet of 30+ aircraft, 100+ staff. Australia''s largest GA company by fleet. Fly Tiwi subsidiary operates 60+ flights/week to Tiwi Islands and Arnhem Land communities. Darwin based.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('HM Air (formerly Katherine Aviation)','hm-air','NT','Katherine / Darwin / Gove','YPTN',-14.5211,132.3778,'https://www.hmair.com.au/','08 8975 0777','fixedwing@hmair.com.au',NULL,'Multiple GA types','Charter, freight','Unknown',NULL,'Possibly','No','fixed_wing',false,'Katherine Aviation flights now operated by HM Air since Dec 2023. Services across NT including Darwin, Katherine, Gove, Alice Springs, Victoria River Downs. Remote community specialist.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('NT Air Services (NTAS)','nt-air-services','NT','Alice Springs','YBAS',-23.8067,133.9019,'https://www.ntas.com.au','08 8952 4288','info@flyntas.com.au',NULL,'Multiple GA types','Charter, RPT','Unknown',NULL,'Possibly','No','fixed_wing',false,'100% Indigenous-owned and operated. Regular public transport across Central Australia. Community-focused operations.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Outback Spirit Tours','outback-spirit-tours','NT','Darwin','YPDN',-12.4147,130.8769,NULL,NULL,NULL,'Owned by Journey Beyond','C210, C208','Tourism charter','Unknown',NULL,'Unknown','No','fixed_wing',false,'Scenic/tourism focus across the Top End. C210 and C208 roles advertised on Indeed periodically.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Alice Springs','rfds-alice-springs','NT','Alice Springs','YBAS',-23.8067,133.9019,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Darwin','rfds-darwin','NT','Darwin','YPDN',-12.4147,130.8769,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('360 Barkly Aviation','360-barkly-aviation','QLD','Mount Isa','YBMA',-20.6636,139.4886,'https://360barklyaviation.com.au/',NULL,NULL,NULL,'C210, C206','Charter, freight','Unknown',NULL,'Possibly','No','fixed_wing',false,'NW QLD charter operations. Mining and community services.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('A.S. Flying School','as-flying-school','QLD','Brisbane (Archerfield)','YBAF',-27.5703,153.0078,'https://asflyingschool.com/',NULL,NULL,NULL,'Light GA training fleet','Training (RPL, PPL, CPL, Instrument Ratings)','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Archerfield-based school offering RPL to CPL training in Class D controlled airspace. One-on-one instruction with flexible scheduling. Glass cockpit training available.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Airways Aviation - Archerfield','airways-aviation-archerfield','QLD','Brisbane (Archerfield)','YBAF',-27.5703,153.0078,'https://www.airwaysaviation.com/','+61 7 5599 3445','australia@airwaysaviation.com',NULL,'C172, multi-engine, simulator fleet','Training (integrated CPL, ATPL, airline pathway)','N/A',NULL,'N/A','Yes (142)','fixed_wing',true,'International aviation academy with campuses at Archerfield, Gold Coast, and Lismore. Integrated airline cadet pathway targeting Australian and Asia-Pacific carriers. Part 142 integrated training. Modern facilities at Archerfield next to Brisbane CBD.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Alliance Aviation','alliance-aviation','QLD','Brisbane (Archerfield)','YBAF',-27.5703,153.0078,'https://www.allianceairlines.com.au','07 3212 1212',NULL,NULL,'Fokker 70/100, E190','FIFO, charter, wet lease','1500+',1500,'No','No','fixed_wing',false,'Major FIFO and wet lease operator. Fokker and Embraer fleet. Not for low-hour pilots but strong career progression target at 1500+ hours. Brisbane HQ, operates nationally.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Cape Air Transport','cape-air-transport','QLD','Horn Island / Cairns / Mareeba','YHID',-10.5833,142.2175,'https://capeairtransport.com','07 4090 3661',NULL,NULL,'C206, C207','Charter, freight','CPL + 250 hrs + ME endorsement + manual propeller pitch control endorsement',250,'Yes','No','fixed_wing',false,'Oldest and most experienced charter company in the Torres Strait. Operating since 1997. Aircraft and pilots based at Horn Island, Mareeba and Cairns. Services into Southern PNG.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Corporate Air - Brisbane','corporate-air-brisbane','QLD','Brisbane','YBBN',-27.3946,153.1237,'https://corporate-air.com.au/','1300 441 000',NULL,NULL,'Saab 340B, Metro 23, Cessna 441 Conquest, jets','Executive charter, FIFO, aeromedical, freight','1000+',1000,'No','No','fixed_wing',false,'Corporate Air base at Brisbane. Headquartered in Canberra (est. 1972). Parent of Link Airways. One of the longest-running aviation services in eastern/southern Australia. Mix of corporate charter, government, FIFO, freight, aeromedical.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Flight Standards - Archerfield','flight-standards-archerfield','QLD','Brisbane (Archerfield)','YBAF',-27.5703,153.0078,'https://www.flightstandards.com.au/',NULL,NULL,NULL,'C172, C172RG, C210, Cirrus SR-20, C152 Aerobat, Beechcraft Baron','Training (RPL, PPL, CPL, multi-engine, IR, Instructor)','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Brisbane campus of Flight Standards (also in Darwin and Perth). Located next to the Archerfield terminal. Beechcraft Baron for multi-engine and IR training. Archerfield is their CPL training base before students move to NT for completion and industry entry. Pilot supply shop on site.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Hinterland Aviation','hinterland-aviation','QLD','Cairns','YBCS',-16.8858,145.7555,'https://www.hinterlandaviation.com.au','07 4040 1333',NULL,NULL,'C208, Dash 8, GA8 Airvan','RPT, charter, scenic','CPL + 1200 hrs total + 150 hrs planned IFR + 50 hrs total night',1200,'No','No','fixed_wing',false,'Lifeline of FNQ skies. Scheduled services Cairns-Cooktown-Kowanyama-Pormpuraaw, Torres Strait, Palm Island from Townsville. ''Real Airline, Real People, Real On-Time Performance.'' Growing operation.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Machjet International','machjet-international','QLD','Brisbane (Archerfield)','YBAF',-27.5703,153.0078,'https://www.machjet.com.au',NULL,NULL,NULL,'Citation, King Air, Falcon','Executive charter','1000+',1000,'No','No','fixed_wing',false,'Executive charter. Brisbane-based. Career target at higher hours.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('PathFinder Aviation','pathfinder-aviation','QLD','Brisbane (Archerfield)','YBAF',-27.5703,153.0078,'https://www.pathfinderaviation.com.au/',NULL,NULL,NULL,'Light GA training fleet','Training (RPL, PPL, CPL, Instrument Ratings)','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Archerfield-based school focused on personalised one-on-one instruction. Teaches both Recreational and General Aviation from the outset — students learn in the right way from day one. In-cockpit camera recording for post-flight review. RPL to CPL.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Brisbane','rfds-brisbane','QLD','Brisbane','YBBN',-27.3946,153.1237,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Bundaberg','rfds-bundaberg','QLD','Bundaberg','YBUD',-24.9039,152.3194,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Cairns','rfds-cairns','QLD','Cairns','YBCS',-16.8778,145.7499,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Charleville','rfds-charleville','QLD','Charleville','YCVQ',-26.4133,146.2625,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Longreach','rfds-longreach','QLD','Longreach','YLRE',-23.4342,144.2797,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Mount Isa','rfds-mount-isa','QLD','Mount Isa','YBMA',-20.6636,139.4886,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Rockhampton','rfds-rockhampton','QLD','Rockhampton','YBRK',-23.3819,150.4753,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Roma','rfds-roma','QLD','Roma','YROM',-26.545,148.7686,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Townsville','rfds-townsville','QLD','Townsville','YBTL',-19.2525,146.7653,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Seair Pacific','seair-pacific','QLD','Gold Coast (Coolangatta)','YBCG',-28.1644,153.5047,'https://www.seairpacific.com.au','07 5599 9555',NULL,NULL,'C208, GA8 Airvan, BN-2 Islander','Scenic, charter, RPT','CPL + 700 hrs + MECIR + C208/BN2 endorsement (arranged through Seair pre-commencement)',700,'No','No','fixed_wing',false,'Scenic flights Lady Elliot Island. Touring and charter across SE QLD. Regular services to Lady Elliot Island.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Skydive Australia - Airlie Beach','skydive-australia-airlie-beach','QLD','Whitsunday Airport, Flame Tree',NULL,-20.2784,148.7557,'https://www.skydive.com.au',NULL,NULL,NULL,'Cessna 208 Caravan / Twin Otter (varies by location)','Skydive operations','200-250',200,'Yes','No','fixed_wing',false,'National skydive operator. Hires low-hour CPL pilots for jump-plane operations; valued first-job pathway for new commercial pilots.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Skydive Australia - Cairns','skydive-australia-cairns','QLD','Cairns Airport',NULL,-16.8778,145.7499,'https://www.skydive.com.au',NULL,NULL,NULL,'Cessna 208 Caravan / Twin Otter (varies by location)','Skydive operations','200-250',200,'Yes','No','fixed_wing',false,'National skydive operator. Hires low-hour CPL pilots for jump-plane operations; valued first-job pathway for new commercial pilots.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Skydive Australia - Mission Beach','skydive-australia-mission-beach','QLD','Mission Beach (Tully Airport)',NULL,-17.9295,145.9382,'https://www.skydive.com.au',NULL,NULL,NULL,'Cessna 208 Caravan / Twin Otter (varies by location)','Skydive operations','200-250',200,'Yes','No','fixed_wing',false,'National skydive operator. Hires low-hour CPL pilots for jump-plane operations; valued first-job pathway for new commercial pilots.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Skydive Australia - Noosa','skydive-australia-noosa','QLD','Sunshine Coast Airport, Marcoola',NULL,-26.6001,153.0886,'https://www.skydive.com.au',NULL,NULL,NULL,'Cessna 208 Caravan / Twin Otter (varies by location)','Skydive operations','200-250',200,'Yes','No','fixed_wing',false,'National skydive operator. Hires low-hour CPL pilots for jump-plane operations; valued first-job pathway for new commercial pilots.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Skytrans','skytrans','QLD','Cairns / Rockhampton / Townsville','YBCS',-16.8858,145.7555,'https://www.skytrans.com.au','07 4046 2462',NULL,'Alan (CEO), Stuart Friend (Chief Pilot)','Dash 8-200, Dash 8-300, C208, A319 (new)','RPT, charter, FIFO, ACMI','500+',500,'No','No','fixed_wing',false,'Major QLD regional airline. Was briefly rebranded SmartLynx Australia (2025) then reverted. RPT across Cape York and Torres Strait. FIFO charters for mining (Bravus, QGC). Taking over Lord Howe Island flights from QantasLink (Feb 2026). Expanding into A319 jets. Good career progression target.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Torres Strait Air','torres-strait-air','QLD','Horn Island','YHID',-10.5833,142.2175,'https://www.torresair.com','07 4069 2777',NULL,'Daniel Takai (Founder, first TSI CPL)','C206, C207, BN-2 Islander','Charter, community transport','CPL + 1000 hrs total + 100 hrs ME; tropical wet-season VFR or IFR experience preferred. Cadet Pilot Program entry available.',1000,'No','No','fixed_wing',false,'Founded 2013 by Daniel Takai, the first Torres Strait Islander Commercial Pilot. IFR-capable fleet. Inter-island transport for schools, health, community. Known for giving pilots a start.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Virgin Australia','virgin-australia','QLD','Various (national)','YBBN',-27.3842,153.1175,'https://www.virginaustralia.com/au/en/about-us/careers/',NULL,NULL,NULL,'B737','RPT','3000+',3000,'No','No','fixed_wing',false,'Major domestic airline. Pilot roles at 3000+ hours. Long-term career target.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Adelaide Aviation','adelaide-aviation','SA','Adelaide (Parafield)','YPPF',-34.7931,138.6331,'https://www.adelaideaviation.com.au/',NULL,NULL,NULL,'Light GA and multi-engine fleet','Training (PPL, CPL, Instructor, multi-engine)','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'CASA Part 141 approved flight training at Parafield. PPL through to CPL, instructor ratings, and multi-engine endorsements. Smaller, personalised operation — Google reviews are consistently strong.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Arid Air','arid-air','SA','Marree','YMRE',-29.6636,138.0647,'https://aridair.com.au/','0488 444 544',NULL,NULL,'Light GA (scenic fleet)','Scenic, charter','Unknown',NULL,'Possibly','No','fixed_wing',false,'Trading name of Central Eagle Aviation Pty. Ltd. (AOC CASA.AOC.0031). Scenic flights over Lake Eyre, the Marree Man, Birdsville, Innamincka, Dalhousie Springs and the Channel Country. Based at Marree Airport, office next to the Marree Hotel. Word-of-mouth suggests low-hour friendly — unconfirmed from primary source.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Flight Training Adelaide','flight-training-adelaide','SA','Adelaide (Parafield)','YPPF',-34.7931,138.6331,'https://www.ftadelaide.com.au','08 8209 2244',NULL,NULL,'C172, DA40, PA-28, PA-44 twin','Training','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Major Adelaide flight school at Parafield. RPL to CPL. Multi-engine training available.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Parafield Flying Centre','parafield-flying-centre','SA','Adelaide (Parafield)','YPPF',-34.7931,138.6331,'https://parafieldflyingcentre.com.au/',NULL,NULL,NULL,'Light GA training fleet','Training (RPL, PPL, CPL)','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Since 2016. Personalised Part 141 training at Parafield in controlled airspace. Pay-as-you-go pricing. Tailored to students balancing work and study. RPL, PPL and CPL programs including controlled aerodrome and radio endorsements.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Adelaide','rfds-adelaide','SA','Adelaide','YPAD',-34.9458,138.5308,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Port Augusta','rfds-port-augusta','SA','Port Augusta','YPAG',-32.5069,137.7167,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Wrightsair','wrightsair','SA','William Creek / Coober Pedy','YWMC',-28.9167,136.8167,'https://www.wrightsair.com.au','08 8670 7962','info@wrightsair.com.au','Operates under LA & AM Matthews AOC','C210, C206, Piper Aerostar, C208, PA-31','Scenic, charter','100 PIC / 200 total',100,'Yes','No','fixed_wing',false,'One of the best first job options for low-hour pilots. Scenic flights over Lake Eyre, Painted Hills, Coober Pedy. Hires from as low as 100 PIC / 200 total hours. Remote location (William Creek). Award-winning tourism operator. 2016-2018 SA Tourism ''Hall of Fame.''','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('King Island Airlines','king-island-airlines','TAS','King Island / Moorabbin','YKII',-39.8775,143.8781,'https://kingislandair.com.au/',NULL,NULL,NULL,'Piper Chieftain, C206','RPT, charter','Unknown',NULL,'Unknown','No','fixed_wing',false,'King Island services. Small RPT operation.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Par Avion / Airlines of Tasmania','par-avion-airlines-of-tasmania','TAS','Hobart (Cambridge)','YCBG',-42.8361,147.5033,'https://www.paravion.com.au','03 6248 5390',NULL,NULL,'C404 Titan, C206, various light','Scenic, charter','300+',300,'Possibly','No','fixed_wing',false,'Established 1978. Owns Cambridge Aerodrome. Famous scenic flights to Southwest Wilderness / Bathurst Harbour. Charter across TAS. Flight school previously affiliated with University of Tasmania has now closed; operates charter and scenic only.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Launceston','rfds-launceston','TAS','Launceston','YMLT',-41.5453,147.2142,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('CAE Melbourne','cae-melbourne','VIC','Melbourne (Moorabbin)','YMMB',-37.9758,145.0997,'https://www.cae.com/civil-aviation/become-a-pilot',NULL,NULL,NULL,'DA40, DA42, simulator fleet','Training (integrated CPL, ATPL, MPL)','N/A',NULL,'N/A','Yes (142)','fixed_wing',true,'Originally established 1968 as General Flying Services. Now part of CAE Inc, global leader in aviation training. Integrated CPL/ATPL/MPL programs targeting Australian and Asia-Pacific airline careers. Major cadet pipeline. Full-motion simulators on site.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Corporate Air - Melbourne (Essendon)','corporate-air-melbourne','VIC','Melbourne (Essendon)','YMEN',-37.7258,144.9016,'https://corporate-air.com.au/','1300 441 000',NULL,NULL,'Saab 340B, Metro 23, Cessna 441 Conquest, jets','Executive charter, FIFO, aeromedical, freight','1000+',1000,'No','No','fixed_wing',false,'Corporate Air base at Melbourne (Essendon). Headquartered in Canberra (est. 1972). Parent of Link Airways. One of the longest-running aviation services in eastern/southern Australia. Mix of corporate charter, government, FIFO, freight, aeromedical.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Learn to Fly Melbourne','learn-to-fly-melbourne','VIC','Melbourne (Moorabbin)','YMMB',-37.9758,145.0997,'https://learntofly.edu.au/','1300 532 768',NULL,'Nick Harris (Head of Operations)','Diamond DA40, DA42 TwinStar, Sling 2, C172, PA44 Seminole, 8KCAB Super Decathlon','Training (RPL, PPL, CPL, multi-engine, aerobatics)','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Modern fleet including glass-cockpit Diamond DA40 and DA42 TwinStar. Aerobatics training with the Super Decathlon. RPL to CPL including multi-engine and instrument training. Alsim DA42 simulator for IFR. International students welcome.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Moorabbin Flying Services (MFS)','moorabbin-flying-services','VIC','Melbourne (Moorabbin)','YMMB',-37.9758,145.0997,'https://mfs.com.au/',NULL,NULL,'Andrew & Madelaine Johnson (owners)','C172, multi-engine fleet','Training (RPL, PPL, CPL, ATPL, NVFR, IFR, Instructor)','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Established 1993. Premier Moorabbin flight training facility. 2017 and 2018 RAeS/Australian Flying Training Organisation of the Year. RPL to ATPL. Many graduates return as MFS instructors. Strong commercial pilot pipeline. Open 7 days.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Peninsula Aero Club','peninsula-aero-club','VIC','Tyabb / Moorabbin','YTYA',-38.2525,145.1872,'https://pac.asn.au/','03 5977 4100',NULL,NULL,'C172, PA-28, C182','Training','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Aero club with flight training at Tyabb and Moorabbin.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Essendon','rfds-essendon','VIC','Melbourne (Essendon)','YMEN',-37.7281,144.9022,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Mildura','rfds-mildura','VIC','Mildura','YMIA',-34.2292,142.0858,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RVAC Aviation Academy','rvac-aviation-academy','VIC','Melbourne (Moorabbin)','YMMB',-37.9758,145.0997,'https://rvac.com.au/',NULL,NULL,NULL,'Diverse fleet including multi-engine','Training (RPL, PPL, CPL, ATPL, Diploma of Aviation, VCE/tertiary)','N/A',NULL,'N/A','Yes (141/142)','fixed_wing',true,'Royal Victorian Aero Club. 100+ years of aviation history. Part 141 AND 142 accredited. Diploma of Aviation pathway. CASA-approved IFR simulators. VCE and tertiary aviation courses. One of Australia''s most historically significant flying clubs.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Sharp Airlines','sharp-airlines','VIC','Essendon / Hamilton / Launceston / Adelaide / Brisbane','YMEN',-37.7281,144.9022,'https://sharpairlines.com','1300 55 66 94',NULL,NULL,'17x Metro III/23','RPT, FIFO, charter, freight','500+',500,'Possibly','No','fixed_wing',false,'Regional airline. RPT to Flinders Island and King Island from Melbourne, Launceston, Hobart. Major FIFO charter. 17 Metroliner fleet. Adelaide base with 4-6 aircraft. May take lower-hour co-pilots on Metro.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Skydive Australia - Melbourne','skydive-australia-melbourne','VIC','Barwon Heads Airport, Connewarre',NULL,-38.2588,144.4269,'https://www.skydive.com.au',NULL,NULL,NULL,'Cessna 208 Caravan / Twin Otter (varies by location)','Skydive operations','200-250',200,'Yes','No','fixed_wing',false,'National skydive operator. Hires low-hour CPL pilots for jump-plane operations; valued first-job pathway for new commercial pilots.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Air Kimberley','air-kimberley','WA','Broome','YBRM',-17.9475,122.2322,'https://www.airkimberley.com.au','08 9193 7359',NULL,NULL,'C208 Grand Caravan, PA-31 Chieftain, GA8 Airvan, C210, C207, C182','Scenic, charter','CPL + 300 hrs total + 100 hrs PIC + 20 hrs on 200-series + CSU and retractable u/c endorsements + NVFR or IR',300,'Yes','No','fixed_wing',false,'Scenic and remote charter across Australia''s Northwest. Broome and seasonal Drysdale River Station bases. Accepting applications for 2026 season. Strong focus on personality and customer service. Fleet from C182 to C208 Grand Caravan — good progression.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Aviair','aviair','WA','Kununurra / Broome / Karratha','YPKU',-15.7781,128.7075,'https://www.aviair.com.au','08 9168 1333',NULL,'Michael McConachy, Geoff Hamilton (owners)','30+ aircraft incl C208, Baron, King Air, Metro','RPT, charter, scenic, FIFO','500+',500,'Possibly','Yes (Part 42 CAMO, Part 145)','fixed_wing',true,'Kimberley''s premier air charter. 35+ years, 5000 flights/year. Subsidiary of HM Consolidated Group. Part 42 CAMO and Part 145 AMO — highest safety standard in GA. Bases in Kununurra, Broome, Karratha. RPT services Derby-Broome. FIFO for mining. Major employer.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Broome Aviation','broome-aviation','WA','Broome','YBRM',-17.9475,122.2322,'https://www.broomeaviation.com.au',NULL,NULL,NULL,'C210, C206, GA8 Airvan','Scenic, charter','200-300',200,'Yes','No','fixed_wing',false,'Longest serving scenic flight operator in the Kimberley. Known as a ''preferred source of line pilots for major charter and domestic route carriers.'' Good stepping stone. Scenic flights, fishing tours, charter.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Fly Broome','fly-broome','WA','Broome','YBRM',-17.9475,122.2322,'https://www.flybroome.com.au/',NULL,NULL,NULL,'GA types','Seasonal RPT','Unknown',NULL,'Unknown','No','fixed_wing',false,'Seasonal direct flights Broome to Karratha, Port Hedland and regional hubs.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Goldfields Air Services','goldfields-air-services','WA','Kalgoorlie','YPKG',-30.7897,121.4617,'https://www.goldfieldsairservices.com.au/','08 9093 2116',NULL,NULL,'C210, C402','Charter, freight, scenic, training','Unknown',NULL,'Possibly','Yes (142)','fixed_wing',true,'Kalgoorlie-based charter. Goldfields and mining region specialist. Scenic flights over the Super Pit. Part 142 confirmed.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Jandakot Flight Centre','jandakot-flight-centre','WA','Perth (Jandakot)','YPJT',-32.0975,115.8811,'https://jfc.net.au/',NULL,NULL,NULL,'C172, PA-28, C182','Training','N/A',NULL,'N/A','Yes (141)','fixed_wing',true,'Perth''s main flight school at Jandakot. RPL to CPL. Also operates Kookaburra Air for scenic flights.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Kimberley Air Tours','kimberley-air-tours','WA','Kununurra','YPKU',-15.7781,128.7075,NULL,NULL,NULL,NULL,'Floatplane, light aircraft','Scenic tours','Unknown',NULL,'Unknown','No','fixed_wing',false,'Floatplane air tours over Lake Argyle, Ord River. Eastern Kimberley scenic specialist.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Maroomba Airlines','maroomba-airlines','WA','Perth','YPPH',-31.9403,115.9672,'https://www.maroomba.com.au',NULL,NULL,NULL,'Metro, King Air','FIFO, charter','500+',500,'No','No','fixed_wing',false,'Major FIFO charter operator serving WA mining sites. Perth-based. Good target at 500+ hours.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Ningaloo Aviation','ningaloo-aviation','WA','Exmouth (Learmonth)','YPLM',-22.2399,114.0941,'https://ningalooaviation.com.au/',NULL,NULL,'Tiffany (Chief Pilot/Owner)','Single-engine fixed-wing fleet','Scenic, charter, aerial spotting, surveys','Unknown',NULL,'Possibly','No','fixed_wing',false,'Founded 2014. Specialises in Ningaloo Reef scenic flights, whale shark and humpback aerial spotting, and charter linking Exmouth, Coral Bay, Onslow, Karratha and Carnarvon. Owner-operator based at Learmonth.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Broome','rfds-broome','WA','Broome','YBRM',-17.9475,122.2322,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Jandakot','rfds-jandakot','WA','Perth (Jandakot)','YPJT',-32.0975,115.8811,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Kalgoorlie','rfds-kalgoorlie','WA','Kalgoorlie','YPKG',-30.7897,121.4617,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Meekatharra','rfds-meekatharra','WA','Meekatharra','YMEK',-26.6117,118.5483,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('RFDS - Port Hedland','rfds-port-hedland','WA','Port Hedland','YPPD',-20.3778,118.6264,'https://www.flyingdoctor.org.au','1800 625 800',NULL,NULL,'PC-12, King Air B200/B350','Aeromedical','1000+',1000,'No','No','fixed_wing',false,'Iconic Australian aviation institution. Aeromedical operations nationally. Requires 1000+ hours, MECIR. Career target, not entry level.','Vectored Operator Database v3 (May 2026)','2026-05-07',true),
  ('Shine Aviation','shine-aviation','WA','Geraldton / Perth (Jandakot)','YPJT',-32.0975,115.8811,'https://www.shineaviation.com.au',NULL,NULL,NULL,'Metro, King Air, C208','RPT, FIFO, charter, training','500+',500,'Possibly','Yes (141)','fixed_wing',true,'RPT services Geraldton-Carnarvon-Monkey Mia. FIFO mining charter. Perth and Geraldton bases.','Vectored Operator Database v3 (May 2026)','2026-05-07',true);

-- 108 rows inserted. All published=true.